
a: all
all:
	python __main__.py

c: coords
coords:
	python coords.py


cst: constellations
constellations:
	python constellations.py


s: stars
stars:
	python stars.py


r: render
render:
	python render.py
